### ISSUE TITLE
stale data

### ISSUE THREAD

**Issue by bir87** [justmiles/go-markdown2confluence#33]
I constantly get Error updating content: Attempted to update stale data. Try again. is a way  to ignore stale data and upload whatever the user wants irrespective of the page being stale or fresh.

**Comment by justmiles** [comment]
Taking another look at [the docs](https://developer.atlassian.com/cloud/confluence/rest/api-group-content/#api-api-content-id-put) it appears this occurs under two circumstances:

> 1. The page is a draft (draft pages cannot be updated).
> 2. The version property has not been set correctly for the content type.

I suppose we could catch the first one, delete the draft, and attempt the upload again. I don't think this happens often, though.

The second is the one that's problematic. Since we're keeping track of state locally the file/page name needs to be unique across the whole confluence space. If you have two or more files in your project with the same name this tool will attempt to write those files to the same page on Confluence. This causes a race condition that will trigger the second error above as the version has already been incremented.

It's another use-case for tracking state locally. We could also determine if there are non-unique file names and fail fast - more clearly outlining the problem.

Could you confirm my suspicion, though - are there potentially multiple files locally that have the same name?

**Comment by justmiles** [comment]
See https://github.com/justmiles/go-markdown2confluence/issues/63#issuecomment-1871399161
