### ISSUE TITLE
Error while rendering confluence macros

### ISSUE THREAD

**Issue by arcones** [justmiles/go-markdown2confluence#38]
Hello!

I have been trying to insert Confluence macro with the builtin support of markdown2confluence.

Having the markdown file I attached inside [test.zip](https://github.com/justmiles/go-markdown2confluence/files/5831121/test.zip)

I do:

`markdown2confluence --space mySpace --username myUsename --password myPassword --endpoint myWikiEndpoint test.md
`

The command finishes successfully (exit code 0) but when I go to the generated page I see this:

![image](https://user-images.githubusercontent.com/17352086/104935171-2fbb0f00-59ab-11eb-870c-639af15641d6.png)

If I check the generated confluence source code, I can find the following:

```
<h1>Title</h1>
<ac:structured-macro ac:macro-id="566545cd-7ssf-4sssf6-593-8985246769ss" ac:name="code" ac:schema-version="1">
  <ac:parameter ac:name="language">CONFLUENCE-MACRO</ac:parameter>
  <ac:parameter ac:name="theme">Confluence</ac:parameter>
  <ac:parameter ac:name="linenumbers">true</ac:parameter>
  <ac:plain-text-body><![CDATA[ name:toc
  minLevel:2
 ]]></ac:plain-text-body>
</ac:structured-macro>
<h2>Section 1</h2>

```

I am using markdown2confluence 3.1.2 and confluence 7.7.4

If you point me where the problem is, maybe I can even resolve and place a pull request

Apart from this issue, I must say, we're getting a lot of value from this tool, and we thank you @justmiles very much for developing it!

**Comment by justmiles** [comment]
Glad to know this is getting used! I've only actually tested this against confluence cloud. It's quite possible some of the macros are completely different for on-prem deployments. 

To tackle this further try editing the page in confluence directly so that it shows exactly what you expect. Then use the API to pull back that xhtml render that confluence generated.

Once you have that you can compare it with the xhtml generated by the CLI. My first thought is that macro IDs might be different. If so we'd need to come up with a way to support unique IDs across instances.

**Comment by pfault** [comment]
This can actually be fixed by modifying the markdown from this:
````
```CONFLUENCE-MACRO
name:toc
  minLevel:2
```
````
to this:
````
```CONFLUENCE-MACRO
name:toc
schema-version:1
  maxLevel:5
  minLevel:2
```
````

I found this by looking at the README, there is a **full** example which contains she _schema-version_.
The other examples don't which might be a bit misleading in this case I guess.

**Comment by justmiles** [comment]
Updated the README to include the schema-version on all examples.
