### ISSUE TITLE
Error with Bearer token

### ISSUE THREAD

**Issue by Gamma-Software** [justmiles/go-markdown2confluence#54]
Hi,
I want to communicate with a self hosted confluence server "https://confluence.xxx.xxx.com" with a token and I get the same error as #7 (Basic Authentication Failure - Reason : AUTHENTICATION_DENIED).
Here is the command I run:
`markdown2confluence -e 'https://confluence.xxx.xxx.com' -u 'valentin.rudloff@xxx.com' -p 'token' -s 'SPACE' --use-document-title test-markdown.md`
I don't understand the reason why it fails whereas the command below works:
``` bash
curl --request POST \
  --url 'https://confluence.xxx.xxx.com/rest/api/content' \
  --header 'Authorization: Bearer token' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data '{
    "title": "My markdown page",
    "type": "page",
    "space": {
      "key": "SPACE"
    },
    "status": "current",
    "ancestors": [
      {
        "id": "312707572"
      }
    ],
    "body": {
      "storage": {
        "value": "This is a test page",
        "representation": "wiki"
      }
    },
    "metadata": {
      "properties":{
        "editor": {
          "value": "v2"
        }
      }
    }
  }'
```

As you can see I used the Bearer not Basic auth mode.
Related to #52 as well

**Comment by Gamma-Software** [comment]
any idea @justmiles ?

**Comment by justmiles** [comment]
Hey @Gamma-Software. I wrote this using Confluence cloud but happy to take a look at the self-hosted version. Per their docs, authentication against the _cloud_ REST API [only supports basic auth](https://developer.atlassian.com/cloud/confluence/rest/v10/intro/#auth). 

It looks like [basic auth is supported for Confluence Server](https://developer.atlassian.com/server/jira/platform/basic-authentication/). If that's a viable option for you then consider using basic auth, otherwise we'll need to update [justmiles/go-confluence](https://github.com/justmiles/go-confluence/blob/master/client.go#L52) to support the other self-hosted authentication methods.
